# Generated by Django 6.0.1 on 2026-01-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("library_name", models.CharField(max_length=100)),
                ("module_path", models.CharField(max_length=255)),
                ("class_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "unique_together": {("module_path", "class_name")},
            },
        ),
    ]
