# Generated by Django 6.0.1 on 2026-03-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("operation_branch", models.JSONField(default=list)),
                ("start_time", models.DateTimeField()),
                ("elapsed_time", models.DurationField(blank=True, null=True)),
                ("status", models.CharField(max_length=128)),
                ("directory", models.CharField(max_length=512)),
            ],
        ),
    ]
